from .lenient_switch_node import (
    NODE_CLASS_MAPPINGS as SWITCH_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SWITCH_DISPLAY_NAME_MAPPINGS,
)
from .prompt_tabs_node import (
    NODE_CLASS_MAPPINGS as PROMPT_TABS_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_TABS_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**SWITCH_CLASS_MAPPINGS, **PROMPT_TABS_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **SWITCH_DISPLAY_NAME_MAPPINGS,
    **PROMPT_TABS_DISPLAY_NAME_MAPPINGS,
}

# Tells ComfyUI to serve the JS in ./web (the Prompt Tabs frontend widget).
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
